version: '3.7'

services:
  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      analytics:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 4000:4000
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    networks:
      analytics:
        aliases:
          - prometheus

networks:
  analytics:
