global:
  scrape_interval: 3s
  scrape_timeout: 3s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'python-credit-app'
    metrics_path: '/'
    static_configs:
      - targets: ['172.17.0.1:8888']
